blog/urls.py
#!/usr/bin/env python
# encoding: utf-8

from django.urls import path
from django.views.decorators.cache import cache_page
from . import views
from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView

app_name = "blog"
urlpatterns = [
    path(
        r'',
        views.IndexView.as_view(),
        name='index'),
    path(
        r'page/<int:page>/',
        views.IndexView.as_view(),
        name='index_page'),
    path(
        r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
        views.ArticleDetailView.as_view(),
        name='detailbyid'),
    path(
        r'category/<slug:category_name>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail'),
    path(
        r'category/<slug:category_name>/<int:page>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail_page'),
    path(
        r'author/<author_name>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail'),
    path(
        r'author/<author_name>/<int:page>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail_page'),
    path(
        r'tag/<slug:tag_name>.html',
        views.TagDetailView.as_view(),
        name='tag_detail'),
    path(
        r'tag/<slug:tag_name>/<int:page>.html',
        views.TagDetailView.as_view(),
        name='tag_detail_page'),
    path(
        'archives.html',
        cache_page(
            60 * 60)(
            views.ArchivesView.as_view()),
        name='archives'),
    path(
        'links.html',
        views.LinkListView.as_view(),
        name='links'),
    path(
        r'upload',
        views.fileupload,
        name='upload'),
    path(
        r'refresh',
        views.refresh_memcache,
        name='refresh')]

core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from core.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from core.feeds import CoreFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from core.admin_site import admin_site
from django.urls import include, path

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
    url(r'^admin/', admin_site.urls),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'mdeditor/', include('mdeditor.urls')),
    url(r'', include('comments.urls', namespace='comment')),
    url(r'', include('accounts.urls', namespace='account')),
    url(r'', include('oauth.urls', namespace='oauth')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^feed/$', CoreFeed()),
    url(r'^rss/$', CoreFeed()),
    url(r'^search', include('haystack.urls'), name='search'),
    url(r'', include('servermanager.urls', namespace='servermanager')),
    url(r'', include('owntracks.urls', namespace='owntracks'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

templates/share_layout/adsense.html
<aside id="text-2" class="widget widget_text">
    <h3 class="widget-title">Google AdSense</h3>
    <div class="textwidget">

        {{ GOOGLE_ADSENSE_CODES }}
    </div>
</aside>

templates/share_layout/analyticscode.html
<script type="text/javascript">
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-27354903-4', 'auto');
    ga('send', 'pageview');
    var _hmt = _hmt || [];
</script>

templates/share_layout/base.html
{% load static %}
{% load cache %}
{% load compress %}
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" lang="id"
      prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" lang="id"
      prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<![endif]-->
<!--[if !(IE 7) & !(IE 8)]><!-->
<html lang="id" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<!--<![endif]-->
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width"/>
    {% block header %}
    {% endblock %}
    <link rel="profile" href="http://gmpg.org/xfn/11"/>

    <!--[if lt IE 9]>
    <script src="{% static 'blog/js/html5.js' %}" type="text/javascript"></script>
    <![endif]-->

    <link rel="alternate" type="application/rss+xml" title="{{ SITE_NAME }} &raquo; Feed"
        href="/feed"/>
    <link rel='stylesheet preload' as="font" id='twentytwelve-fonts-css'
        href="{% static 'blog/fonts/fonts.css' %}" type='text/css' media='all'/>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    {% compress css %}

        <link rel='stylesheet' id='twentytwelve-style-css' href='{% static 'blog/css/style.css' %}' type='text/css'
              media='all'/>
        <link href="{% static 'blog/css/oauth_style.css' %}" rel="stylesheet">
        {% comment %}<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>{% endcomment %}
        <!--[if lt IE 9]>
        <link rel='stylesheet' id='twentytwelve-ie-css'  href='{% static 'blog/css/ie.css' %}' type='text/css' media='all' />
        <![endif]-->
        <link rel="stylesheet" href="{% static 'pygments/default.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/nprogress.css' %}">
        {% block compress_css %}
        {% endblock %}
    {% endcompress %}
</head>

<body class="home blog custom-font-enabled">
<div id="page" class="hfeed site">
    <header id="masthead" class="site-header" role="banner">
        <hgroup>
            <h1 class="site-title"><a href="/" title="{{ SITE_NAME }}" rel="home">{{ SITE_NAME }}</a>
            </h1>
            <h2 class="site-description">{{ SITE_DESCRIPTION }}</h2>
        </hgroup>

        {% cache 36000 nav %}
            {% include 'share_layout/nav.html' %}
        {% endcache %}

    </header><!-- #masthead -->
    <div id="main" class="wrapper">

        {% block content %}
        {% endblock %}


        {% block sidebar %}
        {% endblock %}


    </div><!-- #main .wrapper -->
    {% include 'share_layout/footer.html' %}
</div><!-- #page -->

</body>
<footer>
    {% compress js %}
        <script type="text/javascript" src="{% static 'blog/js/jquery-3.6.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'blog/js/nprogress.js' %}"></script>
        <script src="{% static 'blog/js/blog.js' %}" type="application/javascript"></script>
        <script src="{% static 'blog/js/navigation.js' %}" type="application/javascript"></script>
        {% block compress_js %}
        {% endblock %}
    {% endcompress %}
    {% block footer %}
    {% endblock %}
</footer>
</html>

templates/share_layout/base_account.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <meta name="robots" content="noindex">
    <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    {% load compress %}
    {% compress css %}
        <!-- Bootstrap core CSS -->
        <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'blog/css/oauth_style.css' %}" rel="stylesheet">
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="{% static 'assets/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
        <!-- TODC Bootstrap core CSS -->
        <link href="{% static 'assets/css/todc-bootstrap.min.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'assets/css/signin.css' %}" rel="stylesheet">
    {% endcompress %}
    {% compress js %}
        <script src="{% static 'assets/js/ie10-viewport-bug-workaround.js' %}"></script>
        <script src="{% static 'assets/js/ie-emulation-modes-warning.js' %}"></script>
    {% endcompress %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
{% block content %}
{% endblock %}

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

</body>
</html>

templates/share_layout/footer.html
<footer id="colophon" role="contentinfo">
    <div class="site-info" style="text-align: center">
        Copyright&copy;&nbsp;{{ CURRENT_YEAR }}&nbsp;
        <a href="/" target="blank">{{ SITE_NAME }}</a>
        &nbsp;|&nbsp;

        <a href="/sitemap.xml" title="SiteMap" target="_blank">
            SiteMap
        </a>
        &nbsp;|&nbsp;
        <a href="/feed" title="RSS Feed" target="_blank">
            RSS Feed
        </a>
        &nbsp;|&nbsp;
        <a href="/links.html" title="Links" rel="nofollow" target="_blank">
            Links
        </a>
        |&nbsp; Hosting On&nbsp;
        <a href="https://www.linode.com/?r=b0d38794d05ef8816b357a929106e89b7c6452f9" target="blank" rel="nofollow">Linode</a>

        |&nbsp;
        {% comment %}{% include 'share_layout/analyticscode.html' %}{% endcomment %}

    </div>
    <div class="site-info" style="text-align: center">
        Powered by
        <a href="https://www.djangoproject.com/" rel="nofollow" target="blank">Django</a>
        &nbsp;|&nbsp;
        |
        When the main surface is loaded and worn:<!!LOAD_TIMES!!>s
    </div>
    {% if BEIAN_CODE %}
        <div class="site-info" style="text-align: center">
            <a href="https://beian.miit.gov.cn/" rel="nofollow" target="_blank">
                <p style=" height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;">
                    {{ BEIAN_CODE }}
                </p>
            </a>
            {% if BEIAN_CODE_GONGAN and SHOW_GONGAN_CODE %}
                {{ BEIAN_CODE_GONGAN |safe }}
            {% endif %}
        </div>
    {% endif %}
    {% if ANALYTICS_CODE %}
        {{ ANALYTICS_CODE| safe }}
    {% endif %}
</footer><!-- #colophon -->

templates/share_layout/nav.html
<nav id="site-navigation" class="main-navigation" role="navigation">
    <button class="menu-toggle">Menu</button>
    <a class="assistive-text" href="#content" title="跳至正文">Jumping Masafumi</a>
    <div class="menu-%e8%8f%9c%e5%8d%95-container">
        <ul id="menu-%e8%8f%9c%e5%8d%95" class="nav-menu">
            <li id="menu-item-3498"
                class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-3498">
                <a href="/">Home</a></li>

            {% load blog_tags %}
            {% query nav_category_list parent_category=None as root_categorys %}
            {% for node in root_categorys %}
                {% include 'share_layout/nav_node.html' %}
            {% endfor %}
            {% if nav_pages %}
                {% for node in nav_pages %}

                    <li id="menu-item-{{ node.pk }}"
                        class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-{{ node.pk }}">
                        <a href="{{ node.get_absolute_url }}">{{ node.title }}</a>
                    </li>
                {% endfor %}
            {% endif %}
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">

                <a href="{% url "blog:archives" %}">Sentence</a>
            </li>
        </ul>
    </div>
</nav><!-- #site-navigation -->

templates/share_layout/nav_node.html
<li id="menu-item-{{ node.pk }}"
    class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-{{ node.pk }}">
    <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>
    {% load blog_tags %}
    {% query nav_category_list parent_category=node as child_categorys %}
    {% if child_categorys %}

        <ul class="sub-menu">
            {% for child in child_categorys %}
                {% with node=child template_name="share_layout/nav_node.html" %}
                    {% include template_name %}
                {% endwith %}
            {% endfor %}

        </ul>
    {% endif %}
</li>